# Generated by Django 6.0.1 on 2026-01-22 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('django_ledger', '0029_stagedtransactionmodel_matched_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcedocument',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_documents', to='django_ledger.journalentrymodel'),
        ),
        migrations.AddField(
            model_name='sourcedocument',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('PAID', 'Paid')], default='DRAFT', max_length=20),
        ),
    ]
